
--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------
DECLARE
  nb NUMBER;
BEGIN
  SELECT count(*) INTO nb FROM user_tables 
    WHERE TABLE_NAME = 'ITEM';
  IF nb = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE ITEM (
      ITEM_ID NUMBER(20) ,
      RECEIPT_ID VARCHAR(20),
      ITEM_DESC VARCHAR(200),
      PRICE NUMBER NOT NULL,
      EXP_DATE DATE NOT NULL,
      QTY NUMBER NOT NULL,
      ITEM_ADDDATE DATE,
      PRIMARY KEY(ITEM_ID))';
 END IF;
END;
/

--------------------------------------------------------
--  INSERT for Table ITEM
--------------------------------------------------------
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (87,'244','Staff their hand spend business. Task artist walk build everything.',676,to_date('21-JAN-20','DD-MON-RR'),325,to_date('12-APR-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (231,'245','Leg knowledge dream specific.',551,to_date('05-SEP-21','DD-MON-RR'),845,to_date('10-FEB-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (345,'249','American green eye experience method meet debate.',944,to_date('12-DEC-23','DD-MON-RR'),226,to_date('14-MAY-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (105,'250','Night while challenge laugh place.
Glass great since.',412,to_date('29-AUG-23','DD-MON-RR'),732,to_date('12-MAR-22','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (488,'251','Itself section though including. Employee interview just.',775,to_date('11-SEP-23','DD-MON-RR'),689,to_date('08-NOV-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (469,'252','Thought stock bank value pay could. Us consider speech popular.',680,to_date('22-MAY-22','DD-MON-RR'),428,to_date('20-JUL-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (213,'253','Certain series grow democratic. Impact seat green shake protect stuff cell direction.',264,to_date('23-JAN-21','DD-MON-RR'),282,to_date('02-JAN-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (185,'254','Audience third feeling dream way finish. Pick yourself floor dark.',122,to_date('25-MAR-21','DD-MON-RR'),273,to_date('27-DEC-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (404,'255','Woman goal agree rise check. Memory sign improve sell suffer environmental sit parent.',11,to_date('03-MAY-20','DD-MON-RR'),836,to_date('24-MAR-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (441,'256','Position serious so suddenly travel. Talk small young until the window. Benefit card benefit occur.',281,to_date('25-NOV-20','DD-MON-RR'),456,to_date('27-DEC-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (95,'257','Despite spring over mother party. Hold trouble follow help itself toward.',540,to_date('11-JUL-23','DD-MON-RR'),328,to_date('04-AUG-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (211,'259','Color heavy method level. Team program capital place few.',591,to_date('30-APR-22','DD-MON-RR'),453,to_date('16-JAN-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (189,'264','Best article important. Just beyond American safe center city recognize.',500,to_date('12-JUN-24','DD-MON-RR'),349,to_date('28-NOV-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (255,'265','Mr sea to themselves. My raise discover both education study.',82,to_date('29-MAY-21','DD-MON-RR'),827,to_date('01-DEC-10','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (74,'268','Star option hundred. Its office and claim cover goal.',84,to_date('26-OCT-22','DD-MON-RR'),450,to_date('08-DEC-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (129,'270','Goal lose product rather black. Big me think debate moment tax.',153,to_date('18-JUN-21','DD-MON-RR'),496,to_date('19-MAR-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (320,'271','Indeed must either. Much whom interesting who. Authority activity son determine dream agreement.',43,to_date('28-FEB-23','DD-MON-RR'),500,to_date('21-NOV-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (271,'272','Never card think weight experience. While rule there within college.',122,to_date('12-FEB-23','DD-MON-RR'),279,to_date('17-AUG-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (127,'273','Close identify yeah much. Size relate keep so executive Republican address.',28,to_date('06-FEB-22','DD-MON-RR'),529,to_date('21-APR-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (35,'274','Lawyer old space air range hold.',347,to_date('18-MAY-24','DD-MON-RR'),308,to_date('29-NOV-10','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (484,'275','Nor case majority.
Pay themselves nothing. Model piece painting environmental not keep.',464,to_date('09-SEP-22','DD-MON-RR'),766,to_date('21-MAY-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (68,'277','Site walk page case sense. Successful high green commercial information if successful.',931,to_date('23-APR-20','DD-MON-RR'),245,to_date('11-JUL-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (196,'282','Brother kitchen natural summer difference over. Pick seat fill than form lay.',28,to_date('22-JAN-24','DD-MON-RR'),645,to_date('11-MAR-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (125,'284','Spend contain point man.',349,to_date('06-AUG-20','DD-MON-RR'),259,to_date('23-FEB-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (151,'285','Senior ahead room quickly deal rock glass. Major every second magazine do material few.',85,to_date('25-MAR-20','DD-MON-RR'),373,to_date('15-DEC-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (97,'287','Church list middle economic. Either nor same condition toward support.',494,to_date('22-MAY-20','DD-MON-RR'),384,to_date('19-JAN-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (44,'290','Least side decision thus. Customer garden owner.',403,to_date('03-SEP-22','DD-MON-RR'),909,to_date('16-FEB-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (236,'292','Idea on evidence while expect anything. Down buy how. Statement task doctor garden.',910,to_date('30-NOV-21','DD-MON-RR'),707,to_date('11-FEB-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (280,'293','Probably big assume easy know. Huge become tell give step.',952,to_date('04-AUG-20','DD-MON-RR'),368,to_date('11-JUN-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (443,'294','Film section media how my lose. Building year international skill.',948,to_date('02-SEP-24','DD-MON-RR'),750,to_date('17-DEC-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (495,'296','Ask manager center some policy. Recently despite need continue really forward east reach.',776,to_date('17-OCT-20','DD-MON-RR'),323,to_date('06-MAY-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (239,'297','Fine itself scene the rest strategy history. Enjoy quite sign choose watch think statement.',580,to_date('20-SEP-21','DD-MON-RR'),831,to_date('22-NOV-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (352,'298','Detail win it wonder. Figure Mrs group maintain.',411,to_date('26-JUL-22','DD-MON-RR'),889,to_date('04-AUG-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (325,'300','Unit floor bit should once they. Vote sing far so fall owner option.',986,to_date('21-AUG-24','DD-MON-RR'),153,to_date('31-MAR-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (457,'302','Firm decision behavior sign. Address cold particular modern budget toward report difficult.',879,to_date('20-NOV-22','DD-MON-RR'),880,to_date('21-SEP-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (147,'303','Board feeling fill draw start marriage. Growth another exactly not still fund.',339,to_date('06-JUN-23','DD-MON-RR'),304,to_date('23-NOV-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (136,'304','Memory majority case save. Tv most sound full reach.',177,to_date('25-MAY-21','DD-MON-RR'),371,to_date('08-NOV-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (293,'309','Raise course model each option relationship contain voice.',807,to_date('22-OCT-20','DD-MON-RR'),430,to_date('21-DEC-10','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (200,'310','Political fish join career again. Bag wear she night. Political available because.',987,to_date('29-JUL-20','DD-MON-RR'),884,to_date('11-JUN-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (343,'313','Pattern physical sit. Manage board something trial red hard. Certain speech fund report.',823,to_date('23-JAN-21','DD-MON-RR'),732,to_date('24-OCT-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (67,'314','Commercial realize religious government alone. Yard job try join get foot two.',993,to_date('09-JAN-21','DD-MON-RR'),299,to_date('27-FEB-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (354,'315','Despite bad shoulder appear seem born. Picture sign well less consider century.',497,to_date('13-SEP-21','DD-MON-RR'),754,to_date('07-MAR-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (57,'316','Office point actually throughout agency old. Again sit always choice. Real recent best truth plan.',167,to_date('05-AUG-23','DD-MON-RR'),426,to_date('21-NOV-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (187,'318','Rate while common claim drug. Form cup tell camera break. Imagine turn strong on.',23,to_date('27-APR-22','DD-MON-RR'),663,to_date('15-JUN-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (363,'319','Get month light name. Miss start those price.',54,to_date('28-JUN-24','DD-MON-RR'),935,to_date('12-JUN-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (194,'323','History drop speech use amount herself. Point ok single why blood stay information as.',72,to_date('29-JAN-24','DD-MON-RR'),569,to_date('27-SEP-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (144,'328','Building full media care ten game power what. Positive may interest kid. Mean yes service.',312,to_date('31-OCT-20','DD-MON-RR'),364,to_date('19-OCT-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (36,'329','That season feeling PM.',280,to_date('29-MAR-22','DD-MON-RR'),172,to_date('25-NOV-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (172,'332','Cost say chance cause report history dog affect.
Expert nature return movement never today.',239,to_date('07-DEC-22','DD-MON-RR'),185,to_date('01-NOV-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (89,'333','Have long management need peace mention. Staff support fight young able. Should perform town.',49,to_date('16-DEC-24','DD-MON-RR'),179,to_date('20-MAY-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (474,'335','Check so recently her. More born same report measure. Truth sure experience significant this.',55,to_date('12-JAN-21','DD-MON-RR'),661,to_date('14-OCT-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (2,'336','Rich real remain modern opportunity why break.',335,to_date('24-JUN-24','DD-MON-RR'),326,to_date('13-APR-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (477,'337','Stop red go since claim cold.
Wide accept treatment those. Site we fine specific onto social.',626,to_date('06-APR-21','DD-MON-RR'),291,to_date('19-NOV-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (458,'339','Detail away go each this. What to condition safe field.',798,to_date('29-MAY-20','DD-MON-RR'),224,to_date('03-SEP-10','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (258,'340','Soon war by none try become magazine thousand. Republican four weight.',595,to_date('20-FEB-23','DD-MON-RR'),269,to_date('24-OCT-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (288,'341','Mrs must follow. Anything rich keep her. Politics peace lawyer.',430,to_date('16-JUN-20','DD-MON-RR'),457,to_date('13-DEC-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (398,'342','Western share over test bit change follow. Carry have authority hair green someone.',449,to_date('10-APR-21','DD-MON-RR'),922,to_date('21-DEC-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (18,'344','Federal politics charge. Training indicate wait skill.',523,to_date('27-FEB-21','DD-MON-RR'),449,to_date('14-FEB-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (130,'345','Just child forward ago fight serve. Perhaps conference cut wind. Power any degree firm term.',991,to_date('31-OCT-22','DD-MON-RR'),933,to_date('09-JAN-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (423,'348','Policy light point book successful. Vote design point wide.',96,to_date('23-FEB-20','DD-MON-RR'),145,to_date('07-DEC-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (264,'350','Face subject guess morning my. Bag wide chair me.',757,to_date('18-OCT-21','DD-MON-RR'),713,to_date('04-NOV-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (351,'351','Anyone student national success item again. Husband recently garden government next Mrs vote.',712,to_date('12-OCT-21','DD-MON-RR'),550,to_date('11-JUL-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (217,'357','Deal glass hospital able window decade. Protect computer agency hospital any investment population.',518,to_date('19-DEC-20','DD-MON-RR'),510,to_date('17-NOV-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (173,'359','Pattern main everything realize either now subject. Back recently each simple whom.',893,to_date('01-FEB-22','DD-MON-RR'),238,to_date('14-SEP-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (237,'360','Crime person detail model glass. Statement simply main moment popular official.',364,to_date('01-JAN-20','DD-MON-RR'),491,to_date('08-APR-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (179,'365','Through politics gas become government back training. Remain design cold common.',813,to_date('18-MAY-21','DD-MON-RR'),775,to_date('08-FEB-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (375,'366','Unit mission majority husband. Out beyond popular according thus modern.',697,to_date('12-FEB-20','DD-MON-RR'),230,to_date('29-SEP-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (148,'367','Tend key brother cover when any lose. Including near first. Within might especially.',210,to_date('23-MAY-20','DD-MON-RR'),181,to_date('28-DEC-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (143,'368','Building hour read nice. Look own wall three Republican.',984,to_date('01-JUN-24','DD-MON-RR'),499,to_date('03-AUG-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (56,'370','Cause method finish much. Page newspaper market scientist wall suggest.',374,to_date('08-MAY-22','DD-MON-RR'),150,to_date('27-FEB-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (145,'371','Us assume husband much community. Maintain wife they development serve strong.',973,to_date('22-JUL-22','DD-MON-RR'),837,to_date('11-FEB-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (303,'372','City they order unit wrong none generation.',300,to_date('11-APR-24','DD-MON-RR'),240,to_date('22-FEB-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (263,'373','Story anyone rest. All film answer foreign anything age. Simple already notice threat fund.',403,to_date('12-JUL-22','DD-MON-RR'),156,to_date('24-OCT-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (14,'374','For appear consumer blue laugh reflect rise. Minute plant country federal health appear church.',891,to_date('24-NOV-24','DD-MON-RR'),512,to_date('24-OCT-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (452,'375','Writer assume player project over student. Suggest condition yeah stage.',946,to_date('13-JUN-22','DD-MON-RR'),576,to_date('05-SEP-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (439,'377','Summer work PM commercial pressure red beat. Pattern Republican leg.',686,to_date('11-AUG-21','DD-MON-RR'),992,to_date('15-JUN-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (415,'380','Run provide class produce. With bag prove fly board.',642,to_date('28-JUL-21','DD-MON-RR'),476,to_date('14-FEB-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (361,'382','Sometimes project type.
Themselves energy show act art much. Already top decade bit.',243,to_date('11-JAN-24','DD-MON-RR'),894,to_date('05-MAR-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (382,'383','Perform capital air ok recent own sit.
Adult use support table a.',318,to_date('13-AUG-21','DD-MON-RR'),762,to_date('19-MAR-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (101,'384','Particularly total add debate church north say late. Future step Congress market measure.',892,to_date('12-JUN-20','DD-MON-RR'),145,to_date('10-SEP-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (493,'387','Stay operation answer. Maybe cold sense general.',630,to_date('24-OCT-22','DD-MON-RR'),811,to_date('27-JUN-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (168,'388','Son base security drop staff. Require turn writer hotel property team. Religious order couple run.',918,to_date('26-DEC-23','DD-MON-RR'),618,to_date('16-FEB-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (11,'391','Situation career federal push smile piece. Fill paper either join crime.',478,to_date('12-OCT-20','DD-MON-RR'),461,to_date('28-DEC-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (161,'392','Hotel magazine admit energy catch economic.',968,to_date('11-MAY-24','DD-MON-RR'),454,to_date('13-APR-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (85,'393','Friend six exactly thank research. Girl gas care key right industry. There design leave away.',359,to_date('06-SEP-22','DD-MON-RR'),152,to_date('26-OCT-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (395,'396','Lose after theory catch teach. Stage deal forward past.',797,to_date('10-APR-21','DD-MON-RR'),361,to_date('01-APR-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (88,'399','Push stage control. Perform maybe population surface idea.',446,to_date('22-MAY-24','DD-MON-RR'),803,to_date('02-MAR-22','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (141,'401','Suggest evening into example charge quickly hair. Usually money these research.',632,to_date('16-NOV-22','DD-MON-RR'),510,to_date('06-DEC-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (496,'405','Turn set surface outside moment.',735,to_date('02-JUN-22','DD-MON-RR'),811,to_date('19-DEC-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (364,'407','Example day writer. West strong boy forget.
Rise sound yet dream.',166,to_date('06-JUN-24','DD-MON-RR'),798,to_date('01-DEC-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (374,'411','Specific save property although activity two. Dream although firm including sister information.',394,to_date('28-MAR-21','DD-MON-RR'),267,to_date('21-MAR-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (254,'412','Piece fine others. Time ball compare purpose natural couple attack.',472,to_date('25-OCT-22','DD-MON-RR'),176,to_date('19-MAR-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (284,'416','Woman together none appear adult. Nature pattern degree officer. Would a eye more reason north.',793,to_date('08-JUN-22','DD-MON-RR'),324,to_date('17-MAY-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (91,'422','Follow leave main need make professional law. End too imagine local remain spring.',668,to_date('16-OCT-20','DD-MON-RR'),732,to_date('18-DEC-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (472,'423','Pull physical head rock. Ground stop seem.',624,to_date('28-MAR-22','DD-MON-RR'),303,to_date('29-OCT-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (437,'424','Notice lose thank structure middle. Public state catch term wait sound.
Good floor stand sea piece.',964,to_date('27-FEB-22','DD-MON-RR'),559,to_date('23-NOV-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (114,'426','Rest let assume effect oil. Size southern billion own election piece professional.',1000,to_date('10-MAR-21','DD-MON-RR'),132,to_date('29-SEP-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (468,'427','Set book enjoy tough gun big. Simple serve recent health. North garden usually different visit.',762,to_date('16-DEC-24','DD-MON-RR'),222,to_date('17-MAY-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (212,'429','Imagine fish ever my certain finally. Hard media sure continue foot. Right service cut sit fine.',555,to_date('14-NOV-20','DD-MON-RR'),740,to_date('19-MAR-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (153,'430','Serious write church blue true.',104,to_date('31-DEC-23','DD-MON-RR'),668,to_date('07-MAR-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (365,'431','Left later public. Dream serious election professor vote.',44,to_date('16-JUL-22','DD-MON-RR'),426,to_date('28-SEP-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (298,'433','Thousand ask pattern black truth sometimes pull.',148,to_date('03-MAR-20','DD-MON-RR'),869,to_date('18-DEC-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (310,'435','Forward meeting imagine ago hand yes nice. Now but partner wrong. During third challenge list.',308,to_date('01-MAY-21','DD-MON-RR'),367,to_date('04-DEC-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (107,'439','Five compare side newspaper baby themselves image. Big argue yard mission knowledge worry friend.',29,to_date('12-APR-20','DD-MON-RR'),931,to_date('17-MAY-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (301,'440','Toward show view property. Level outside six political. Camera week each born.',528,to_date('01-SEP-20','DD-MON-RR'),957,to_date('19-NOV-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (150,'442','Place serve task evening figure show. Eight business decision machine.',625,to_date('10-FEB-21','DD-MON-RR'),554,to_date('02-NOV-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (270,'444','Boy successful manage fish increase hospital figure. Long hold personal woman major.',691,to_date('28-JAN-20','DD-MON-RR'),920,to_date('28-NOV-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (314,'445','Reality mouth others coach book. Spend hard even form pay population star record.',829,to_date('19-MAY-20','DD-MON-RR'),370,to_date('19-MAR-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (269,'449','Stock everything into. Artist visit seem require word myself listen.',245,to_date('12-DEC-20','DD-MON-RR'),984,to_date('06-DEC-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (225,'453','Firm on bad treatment bit situation name. Away arm lawyer add form.',286,to_date('12-MAR-23','DD-MON-RR'),545,to_date('28-APR-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (487,'456','Fast attorney room if before. Break behind next friend anyone Mr. Dog role film beautiful.',764,to_date('22-JUN-24','DD-MON-RR'),557,to_date('12-OCT-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (69,'461','Enough always a glass explain remain maintain list. Difficult system ago field.',339,to_date('17-JUL-22','DD-MON-RR'),602,to_date('22-JUN-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (412,'465','Deal pay necessary property travel win. Cultural base music consumer.',623,to_date('19-JAN-22','DD-MON-RR'),286,to_date('22-MAR-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (245,'466','Simple agent lead own set over. Sound others certain design have have onto.',709,to_date('11-OCT-22','DD-MON-RR'),966,to_date('10-MAY-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (193,'472','Professor technology serious science safe movie.',628,to_date('26-AUG-24','DD-MON-RR'),131,to_date('14-AUG-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (418,'473','Hold quite compare this yourself with member. Stop between hope say event our method.',870,to_date('26-MAR-22','DD-MON-RR'),411,to_date('23-JUL-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (295,'475','Film serious Mr wife others. Protect beyond represent responsibility pick paper.',247,to_date('30-NOV-22','DD-MON-RR'),276,to_date('17-MAY-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (268,'476','Feeling allow show put respond. Toward very team source west different.',559,to_date('27-JUN-23','DD-MON-RR'),180,to_date('13-APR-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (333,'479','Likely range matter ground.
Behind street student. Fill huge onto collection health follow.',557,to_date('21-OCT-23','DD-MON-RR'),967,to_date('25-DEC-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (133,'480','Toward economy spring far glass season serious. Catch body onto them partner the without tree.',768,to_date('11-AUG-23','DD-MON-RR'),937,to_date('25-OCT-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (100,'482','Apply can choice open. Exactly national many represent nothing price.',587,to_date('26-JAN-20','DD-MON-RR'),678,to_date('29-NOV-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (31,'484','Say car gun fight game bar. Painting town director present adult still total.',156,to_date('14-MAY-22','DD-MON-RR'),422,to_date('19-OCT-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (275,'489','Information value address two policy fund those. All receive town.',217,to_date('29-MAY-24','DD-MON-RR'),752,to_date('09-NOV-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (445,'490','Get response executive media approach player rise. The Mrs particular modern past.',606,to_date('09-DEC-22','DD-MON-RR'),179,to_date('01-FEB-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (214,'491','Give it activity hour. Perhaps party former those.',867,to_date('07-MAR-24','DD-MON-RR'),748,to_date('19-JUN-10','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (466,'492','Court protect staff success everybody. Summer see form brother responsibility. Themselves cup at.',726,to_date('25-JUL-21','DD-MON-RR'),765,to_date('03-MAY-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (407,'493','Investment even shoulder them less. Try nor staff per instead. Upon someone hear up north.',899,to_date('22-JUN-23','DD-MON-RR'),112,to_date('19-NOV-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (446,'496','Card wife campaign step require center. Pass political suffer back do.',788,to_date('03-OCT-20','DD-MON-RR'),464,to_date('04-AUG-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (426,'499','Majority add fact door bit early seat.',573,to_date('05-JUL-21','DD-MON-RR'),493,to_date('07-DEC-10','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (347,'1','Difference big add when whose check my. Character blue statement real medical tonight.',456,to_date('15-SEP-24','DD-MON-RR'),332,to_date('23-NOV-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (121,'2','Business rest view third. Black character blue out affect game raise.
Drug learn audience change.',693,to_date('28-JAN-22','DD-MON-RR'),948,to_date('28-NOV-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (272,'3','Draw source want education. Appear around might. Quality join ask trip institution idea every.',134,to_date('10-NOV-24','DD-MON-RR'),883,to_date('31-JUL-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (232,'4','Debate people word economic. Early exactly PM road.
Continue serious job movement.',312,to_date('16-JAN-23','DD-MON-RR'),689,to_date('02-NOV-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (380,'5','Pass those the up stock. Yeah our tend like bill ground check get.',595,to_date('13-NOV-24','DD-MON-RR'),885,to_date('14-JAN-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (340,'6','Theory different firm national senior. Loss out woman quite too.',599,to_date('13-APR-24','DD-MON-RR'),446,to_date('06-JAN-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (55,'7','Cause bed class. Move everything same key child mean positive.',485,to_date('05-JUN-22','DD-MON-RR'),849,to_date('23-NOV-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (416,'8','Before someone magazine past network Mrs develop budget.',731,to_date('28-JAN-21','DD-MON-RR'),345,to_date('09-AUG-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (40,'9','Similar enter become result. Like here popular foreign behind she seven.',397,to_date('24-OCT-21','DD-MON-RR'),330,to_date('20-JUL-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (479,'10','Wind appear American spring. Once question pull or day doctor.',783,to_date('05-FEB-22','DD-MON-RR'),362,to_date('12-APR-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (492,'11','Floor protect radio new rock deal. Hit suddenly system.',677,to_date('11-OCT-21','DD-MON-RR'),752,to_date('04-AUG-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (152,'12','Great police ground eight reveal. Student kid language loss professor if enter dream.',799,to_date('04-FEB-22','DD-MON-RR'),284,to_date('19-OCT-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (186,'13','Focus serious cultural. With left light cover community truth nature.',157,to_date('25-JAN-22','DD-MON-RR'),910,to_date('01-OCT-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (370,'14','Large sister I put serve. Look school north stand card.',433,to_date('12-JAN-20','DD-MON-RR'),276,to_date('03-APR-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (235,'15','Middle no tree everybody.
Cost computer pressure. Ability single since almost according effort.',634,to_date('11-JUN-23','DD-MON-RR'),195,to_date('06-MAR-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (51,'17','Risk hot term fast all economy federal. Vote let indeed reduce.',603,to_date('27-MAY-20','DD-MON-RR'),260,to_date('15-AUG-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (373,'18','Woman apply above. Tonight woman gun fly ready.',219,to_date('17-JAN-23','DD-MON-RR'),969,to_date('20-FEB-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (360,'19','Listen plan situation ahead. Ok thousand girl.',195,to_date('08-JUN-20','DD-MON-RR'),967,to_date('26-JUL-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (291,'21','Along place care near site federal on again. Effect word tend country different pay.',921,to_date('10-JAN-24','DD-MON-RR'),943,to_date('28-APR-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (433,'22','Idea billion life account one again.',123,to_date('25-OCT-23','DD-MON-RR'),129,to_date('03-JUN-10','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (475,'23','Out their plant really finally. Sport drug magazine article yet other.',571,to_date('15-JAN-20','DD-MON-RR'),550,to_date('12-SEP-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (234,'24','Total throughout pattern. Federal move American deep early make us enter.',62,to_date('04-SEP-23','DD-MON-RR'),943,to_date('14-OCT-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (282,'25','Decision charge modern my age lead.',579,to_date('02-OCT-22','DD-MON-RR'),230,to_date('09-APR-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (366,'26','Shoulder check worker player into professor can. Clearly positive short wife people suffer.',276,to_date('12-JUN-23','DD-MON-RR'),906,to_date('15-OCT-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (201,'27','Region out exist half. Model experience old night. Career language hotel one dream suggest.',566,to_date('15-SEP-22','DD-MON-RR'),855,to_date('20-AUG-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (281,'28','Environmental provide crime. Table our inside language star health.',598,to_date('15-JUN-23','DD-MON-RR'),219,to_date('16-NOV-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (276,'29','The hand push bag national. Physical business PM process. Take election bag others green.',952,to_date('17-OCT-23','DD-MON-RR'),567,to_date('13-DEC-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (290,'30','Project more know over issue. Clear science success region. Scene at front but TV financial meet.',502,to_date('06-NOV-21','DD-MON-RR'),253,to_date('21-SEP-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (257,'31','Senior section yeah meeting local herself. Reach owner market every actually.',24,to_date('22-AUG-20','DD-MON-RR'),170,to_date('10-FEB-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (302,'32','Out fact unit window. Policy someone record alone paper. Group foot yourself.',139,to_date('27-FEB-24','DD-MON-RR'),246,to_date('11-JUN-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (449,'33','Response together lead tonight reflect. Home present admit boy.',343,to_date('13-MAY-24','DD-MON-RR'),735,to_date('23-NOV-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (252,'34','Also ask specific address adult. Current anyone off might. Rest soon method church.',72,to_date('19-FEB-21','DD-MON-RR'),782,to_date('19-MAR-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (432,'35','Enough hard customer right. Many show today outside management. Point budget name.',453,to_date('26-APR-22','DD-MON-RR'),494,to_date('20-MAY-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (430,'36','Hear when word short start. Manager line identify weight interesting the.',880,to_date('26-MAY-21','DD-MON-RR'),487,to_date('25-OCT-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (47,'37','Congress itself view night. Reduce wrong campaign.',306,to_date('04-OCT-23','DD-MON-RR'),863,to_date('23-NOV-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (177,'38','Her course civil myself share little. Among prepare soon feel. Follow wide dog.',754,to_date('21-FEB-23','DD-MON-RR'),392,to_date('06-MAR-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (462,'39','Itself find more price. Phone wait air blue opportunity long husband.',13,to_date('25-MAR-23','DD-MON-RR'),373,to_date('22-MAR-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (436,'40','Hot term sell area difference because. Those executive drive article. Mention fight contain.',519,to_date('31-MAY-20','DD-MON-RR'),146,to_date('15-DEC-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (104,'41','Capital night once game. Energy ten ready no.',967,to_date('10-JAN-20','DD-MON-RR'),557,to_date('28-APR-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (341,'42','Age remain material no page control miss. Water address present only peace.',117,to_date('31-OCT-21','DD-MON-RR'),402,to_date('25-MAR-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (209,'43','Bag if rest radio carry. Present option there somebody stay for security cold.',388,to_date('31-DEC-20','DD-MON-RR'),645,to_date('28-APR-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (230,'44','Movement that ball including. Stay surface range perform hot its. Good decision somebody.',228,to_date('30-AUG-22','DD-MON-RR'),617,to_date('09-APR-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (389,'45','Create capital past reality. Above production put dark. Manager feel trip eight century mission.',85,to_date('15-DEC-23','DD-MON-RR'),517,to_date('01-DEC-10','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (377,'46','Imagine reach there glass Democrat. Population face individual impact my. Writer know your sound.',526,to_date('19-SEP-21','DD-MON-RR'),411,to_date('26-FEB-22','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (260,'47','Or bag similar particularly rock figure bit.',703,to_date('24-MAR-24','DD-MON-RR'),992,to_date('26-JUL-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (429,'48','Language majority final answer history. Artist learn star night performance.',1000,to_date('05-JUN-22','DD-MON-RR'),420,to_date('07-APR-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (128,'49','Soldier off whether. Even chair article since even cell. Soon left eat cold health.',880,to_date('20-OCT-21','DD-MON-RR'),734,to_date('29-SEP-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (10,'50','Eye manager commercial doctor language thank. Until trial grow the husband.
Degree or way.',768,to_date('22-MAR-24','DD-MON-RR'),471,to_date('12-MAR-22','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (384,'51','Final rate fall although. Happen avoid then fill.',17,to_date('05-AUG-21','DD-MON-RR'),713,to_date('19-JAN-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (226,'52','Stuff hair middle include yourself. Wish interesting clear nation majority difficult.',183,to_date('11-DEC-20','DD-MON-RR'),339,to_date('08-NOV-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (240,'54','Expect arrive then financial firm. Shoulder deep interesting democratic effort guess.',513,to_date('03-FEB-20','DD-MON-RR'),843,to_date('10-SEP-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (470,'55','Answer physical sport include wife baby organization. Just suddenly want today.',920,to_date('04-JUL-20','DD-MON-RR'),231,to_date('12-DEC-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (50,'56','Senior region within east education seem evening.',271,to_date('26-FEB-22','DD-MON-RR'),573,to_date('10-APR-22','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (21,'57','Exactly company dog leader modern yes benefit. Market until water prove end account too.',703,to_date('19-JUN-22','DD-MON-RR'),672,to_date('23-JUN-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (49,'58','International where fish art ever. Play tree scene analysis yet early language.',653,to_date('28-JUN-24','DD-MON-RR'),791,to_date('01-DEC-10','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (131,'59','Media color else research commercial whose.
Suffer low public include adult back.',549,to_date('26-OCT-20','DD-MON-RR'),593,to_date('21-SEP-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (400,'60','South quickly hold school. Of power organization simple.',785,to_date('07-MAR-20','DD-MON-RR'),649,to_date('29-NOV-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (435,'61','Nearly ok course not. Pull book yard. Chance drug deep live person list.',182,to_date('18-MAR-21','DD-MON-RR'),628,to_date('21-MAY-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (81,'62','Organization room drug bar rock. Social common figure purpose individual fill hospital.',117,to_date('27-NOV-23','DD-MON-RR'),926,to_date('09-JAN-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (190,'63','Drug and effort draw deep base before. Perhaps Republican once almost.',814,to_date('19-SEP-23','DD-MON-RR'),398,to_date('27-FEB-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (103,'64','Reflect if stop daughter me. Arm report professional character bed.',313,to_date('28-JUL-20','DD-MON-RR'),240,to_date('01-MAY-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (478,'65','Finish court operation for store democratic. Surface deep stage north people know experience.',963,to_date('07-JUN-24','DD-MON-RR'),911,to_date('09-JAN-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (251,'66','Outside end past conference strong before. Change enough employee despite drive seat same.',653,to_date('16-DEC-24','DD-MON-RR'),983,to_date('19-DEC-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (66,'67','Develop too generation ask action family. Office whom poor sense.',647,to_date('24-OCT-23','DD-MON-RR'),534,to_date('24-DEC-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (156,'68','Character phone report myself firm unit.',24,to_date('29-JUL-22','DD-MON-RR'),514,to_date('14-FEB-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (300,'71','Example person help.
Professor both determine employee event national character.',328,to_date('02-NOV-23','DD-MON-RR'),677,to_date('04-OCT-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (8,'72','Real conference result reality. A one head southern full. Food economic fish close service.',282,to_date('30-SEP-20','DD-MON-RR'),809,to_date('19-DEC-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (313,'74','Among item bag best. Other season discuss first.',470,to_date('23-SEP-22','DD-MON-RR'),334,to_date('23-FEB-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (227,'75','Simply morning war fact. Enjoy popular seat radio. Fight until most customer necessary trip.',442,to_date('21-MAY-22','DD-MON-RR'),998,to_date('08-APR-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (84,'76','Anything care street such. System around box best in. Religious difficult space conference stand.',242,to_date('25-OCT-20','DD-MON-RR'),953,to_date('19-MAR-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (448,'77','Window say military study should. Cultural western huge nation nor.',75,to_date('11-NOV-20','DD-MON-RR'),940,to_date('12-APR-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (405,'78','Me education catch natural head tell. Want view security easy everyone parent thank represent.',328,to_date('05-AUG-22','DD-MON-RR'),160,to_date('19-OCT-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (54,'79','Machine leg show design. Cover card song send thus. Develop have we chance.',271,to_date('25-MAY-24','DD-MON-RR'),268,to_date('19-JAN-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (326,'80','Letter contain run old section executive. Learn heavy really organization.',836,to_date('17-FEB-23','DD-MON-RR'),1000,to_date('10-OCT-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (183,'81','Book parent picture big blue father.',69,to_date('05-APR-22','DD-MON-RR'),544,to_date('24-DEC-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (394,'82','Behavior choose spring. Miss training own discuss. Agreement within state pass meet second.',713,to_date('18-APR-22','DD-MON-RR'),362,to_date('12-JUN-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (165,'83','Them white hope teach coach word few.
Themselves financial number listen cell heavy.',370,to_date('30-JUL-21','DD-MON-RR'),747,to_date('14-JUN-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (459,'85','Ever will understand responsibility way bar possible.',461,to_date('11-APR-21','DD-MON-RR'),162,to_date('26-AUG-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (491,'86','See market role push morning. Laugh hear forward support side.',867,to_date('02-AUG-24','DD-MON-RR'),102,to_date('04-AUG-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (4,'89','Growth light nor decide field put. Medical fast bring nothing. Show oil enough table court.',637,to_date('28-JAN-20','DD-MON-RR'),111,to_date('09-NOV-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (253,'90','Play wait probably federal. However how investment first yes out me.',606,to_date('04-APR-22','DD-MON-RR'),779,to_date('29-MAY-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (33,'92','Pick very easy easy for its. Pretty which ok believe successful.',752,to_date('05-DEC-23','DD-MON-RR'),914,to_date('10-DEC-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (438,'93','Only stage item bit class rock bed.
Type story drop wrong pressure. Answer traditional gas.',130,to_date('07-DEC-20','DD-MON-RR'),178,to_date('03-MAY-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (164,'94','Week health old see explain throughout sort agency. Thousand west fine.',894,to_date('23-MAY-21','DD-MON-RR'),182,to_date('11-OCT-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (192,'95','Mission statement mother born but. Old rule mention force word.',918,to_date('08-NOV-23','DD-MON-RR'),880,to_date('01-MAR-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (39,'97','Public war anyone relate top power.',841,to_date('30-MAR-20','DD-MON-RR'),466,to_date('27-OCT-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (96,'99','Green test trouble subject fish happen thus.',985,to_date('13-FEB-24','DD-MON-RR'),587,to_date('12-MAR-22','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (170,'100','Even several Democrat. Husband door until smile thought door cover.',938,to_date('03-FEB-23','DD-MON-RR'),333,to_date('19-MAR-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (355,'101','Visit bag performance alone. Few entire should south nature. Personal laugh item region student.',888,to_date('16-NOV-24','DD-MON-RR'),850,to_date('24-DEC-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (76,'102','Live should Republican ahead author value. Plant contain should back military alone what recent.',219,to_date('30-OCT-24','DD-MON-RR'),984,to_date('19-OCT-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (331,'103','American than myself remember medical among. Together tough despite close fill so general.',235,to_date('20-OCT-22','DD-MON-RR'),878,to_date('06-MAY-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (372,'105','Happy challenge eye decade. Nor rock conference want modern. Follow cell occur so very money plan.',429,to_date('13-JUN-23','DD-MON-RR'),240,to_date('31-JUL-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (316,'106','Main thousand according hotel far good event. Late glass base she simply seat chance.',1000,to_date('23-MAY-22','DD-MON-RR'),251,to_date('16-NOV-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (70,'107','Arrive watch four low space purpose down or. She page answer level choice set necessary.',138,to_date('09-APR-24','DD-MON-RR'),960,to_date('19-NOV-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (299,'108','Enough agreement vote offer.',978,to_date('31-AUG-21','DD-MON-RR'),542,to_date('30-MAR-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (286,'109','Risk control tax practice really late back smile. Reflect good set bring late civil direction.',519,to_date('18-MAR-22','DD-MON-RR'),535,to_date('19-APR-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (323,'110','Wonder since image often. Outside pressure against new onto most.',536,to_date('03-APR-20','DD-MON-RR'),223,to_date('20-JUL-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (335,'111','Threat cup positive plant. Charge avoid accept near.',654,to_date('21-APR-23','DD-MON-RR'),762,to_date('18-MAR-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (456,'112','Talk ready speak ten people. Move possible care can.',501,to_date('02-JUL-20','DD-MON-RR'),752,to_date('25-SEP-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (344,'113','Scientist plan professional ahead particular bed more. Send sing agree.',252,to_date('01-JUL-23','DD-MON-RR'),355,to_date('14-MAY-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (34,'114','We easy sister thousand go artist. Exist all building smile yeah. Church PM budget as.',633,to_date('09-DEC-21','DD-MON-RR'),139,to_date('17-MAY-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (490,'115','Sign throw until then court hotel nation. Shake box different million after line.',132,to_date('26-FEB-20','DD-MON-RR'),959,to_date('20-DEC-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (454,'118','List citizen staff hear later economy watch. Rise explain final certain become across music.',681,to_date('23-DEC-23','DD-MON-RR'),610,to_date('14-JAN-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (350,'119','Language clear fire out do. Training tree today.',314,to_date('07-MAR-22','DD-MON-RR'),231,to_date('30-APR-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (229,'120','Writer almost try local else after. Who camera entire others economy.',749,to_date('19-JUN-21','DD-MON-RR'),794,to_date('16-OCT-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (181,'122','Relate case want including establish.',372,to_date('14-APR-20','DD-MON-RR'),280,to_date('06-DEC-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (391,'123','Reflect outside shoulder likely sport culture win. Conference sure number customer cut.',173,to_date('24-MAR-24','DD-MON-RR'),391,to_date('27-FEB-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (26,'124','Small station someone too cause I peace. We evidence human officer hair water relate.',100,to_date('20-MAY-24','DD-MON-RR'),947,to_date('28-SEP-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (296,'125','Two half success over. Leader few catch threat. Case free lot.',806,to_date('03-DEC-22','DD-MON-RR'),541,to_date('06-FEB-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (342,'126','Interest hot instead guy nice start. Material include themselves expect as crime measure.',997,to_date('30-JAN-21','DD-MON-RR'),325,to_date('29-OCT-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (463,'127','Bill natural tonight pay form. Soldier thus drug recent.',51,to_date('24-JAN-20','DD-MON-RR'),136,to_date('23-JUN-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (59,'128','Congress eight improve task standard. Project camera police something media.',448,to_date('05-JUL-22','DD-MON-RR'),107,to_date('27-FEB-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (180,'130','Southern color sort. Total material authority serve kid subject nor cover. Product indicate it eye.',638,to_date('28-JUL-21','DD-MON-RR'),780,to_date('25-DEC-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (29,'131','Cover management yes. Hotel kind quite think.',690,to_date('19-JAN-23','DD-MON-RR'),794,to_date('30-JUN-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (485,'132','Change our clearly enjoy. Officer nature Mrs up start brother eat.',970,to_date('06-DEC-21','DD-MON-RR'),935,to_date('29-MAY-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (12,'133','Civil indicate phone if. Form cultural themselves final.',823,to_date('28-NOV-21','DD-MON-RR'),414,to_date('10-FEB-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (32,'134','Newspaper professional against enter cost. Doctor avoid teacher finish read. Down those money hand.',513,to_date('11-MAR-20','DD-MON-RR'),545,to_date('04-FEB-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (197,'135','Effort surface former base tough. Executive top oil friend. Quality child wait age to truth film.',868,to_date('19-JUN-24','DD-MON-RR'),485,to_date('05-JAN-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (61,'136','Budget believe brother whom.',706,to_date('30-MAY-20','DD-MON-RR'),617,to_date('31-AUG-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (175,'137','Short thus soldier both reflect kind sure. Improve whom stay director treat.',562,to_date('09-FEB-22','DD-MON-RR'),513,to_date('03-NOV-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (42,'139','Hair floor painting hot project structure. Decade central soldier poor majority training section.',909,to_date('11-APR-23','DD-MON-RR'),287,to_date('18-AUG-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (134,'140','Dog knowledge recognize. West simple Democrat various chair force story win.',698,to_date('01-OCT-23','DD-MON-RR'),450,to_date('06-JAN-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (139,'141','Color fire real heavy thought as idea.',206,to_date('17-MAR-24','DD-MON-RR'),869,to_date('03-JUN-10','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (218,'143','Politics left seat cut. Environment case seven bill market throughout.',954,to_date('04-FEB-21','DD-MON-RR'),614,to_date('20-JUN-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (409,'145','Question child son thing less administration. Ground reduce continue miss.',818,to_date('09-DEC-21','DD-MON-RR'),546,to_date('23-AUG-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (392,'146','Mention forget cause leg. Book sea professional benefit effect.',739,to_date('08-AUG-23','DD-MON-RR'),316,to_date('05-MAR-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (419,'148','Medical reach home idea traditional guy. Black we sing.',753,to_date('25-DEC-20','DD-MON-RR'),603,to_date('01-MAR-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (420,'149','Provide evening any standard specific long expect. Detail east life about on week.',974,to_date('03-AUG-23','DD-MON-RR'),641,to_date('25-MAY-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (411,'150','Season his off suddenly social director model.',10,to_date('01-DEC-21','DD-MON-RR'),764,to_date('04-FEB-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (421,'151','Create professor actually property. Learn shake course the. Figure clear design.',733,to_date('04-MAY-20','DD-MON-RR'),563,to_date('11-JUL-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (356,'152','Figure watch eye system.',606,to_date('01-OCT-20','DD-MON-RR'),566,to_date('15-OCT-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (46,'153','Moment already ability central provide general such culture. Particularly certain Republican again.',317,to_date('25-MAY-23','DD-MON-RR'),696,to_date('18-DEC-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (118,'156','Occur pretty all pattern identify.',863,to_date('25-OCT-23','DD-MON-RR'),803,to_date('12-OCT-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (222,'158','Alone technology if society either receive. Point organization real force education wall civil.',570,to_date('13-JAN-24','DD-MON-RR'),254,to_date('02-NOV-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (362,'159','Eat debate somebody customer list head myself. House federal able light. Study give billion.',437,to_date('08-AUG-23','DD-MON-RR'),899,to_date('02-NOV-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (30,'160','Pass house training. True majority property least affect call.',624,to_date('11-MAY-23','DD-MON-RR'),307,to_date('19-MAR-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (434,'161','Indeed three occur benefit. Never including senior office.',681,to_date('11-MAY-24','DD-MON-RR'),518,to_date('17-OCT-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (22,'162','Offer nice let above continue performance shoulder. Mouth catch Congress know great perhaps them.',245,to_date('18-AUG-22','DD-MON-RR'),603,to_date('14-JAN-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (476,'163','Road body real moment. Resource enough space personal husband doctor go.',81,to_date('01-AUG-22','DD-MON-RR'),572,to_date('06-AUG-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (431,'165','Store to prevent share reduce list. You around billion believe movement statement.',771,to_date('14-SEP-23','DD-MON-RR'),537,to_date('25-OCT-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (308,'166','Size vote agency.',672,to_date('19-APR-20','DD-MON-RR'),383,to_date('11-SEP-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (348,'168','If point somebody mind sure get shoulder. Place product bar Republican pick.',167,to_date('24-FEB-24','DD-MON-RR'),279,to_date('15-MAR-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (315,'169','Doctor house suffer. Child PM hundred inside. Strong between report.',809,to_date('07-MAR-20','DD-MON-RR'),642,to_date('17-MAY-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (428,'170','Over whole upon ground scientist. Current party thing several half.',355,to_date('06-APR-20','DD-MON-RR'),520,to_date('17-AUG-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (117,'171','General skill use war front blood door. Ground exist arm girl. Series low late ready.',386,to_date('24-OCT-22','DD-MON-RR'),978,to_date('16-NOV-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (3,'172','To child owner TV phone. Star reflect list for.',990,to_date('28-JUN-24','DD-MON-RR'),121,to_date('24-DEC-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (111,'173','Class billion present community.',638,to_date('19-MAY-24','DD-MON-RR'),940,to_date('02-JUN-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (393,'174','Film member marriage realize suffer station.',582,to_date('02-FEB-23','DD-MON-RR'),666,to_date('02-MAR-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (126,'175','Per cup impact. Key leave best human sense situation most. Agree child interesting design sound.',808,to_date('17-NOV-23','DD-MON-RR'),642,to_date('24-JUN-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (387,'176','Somebody find because may health wind.',814,to_date('10-AUG-23','DD-MON-RR'),639,to_date('03-NOV-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (460,'177','You political majority certain PM. Policy for agent. Big all bag sound.',452,to_date('13-NOV-21','DD-MON-RR'),102,to_date('17-OCT-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (188,'179','Check sell hear where manage station party. More executive great finish myself.',422,to_date('31-JUL-24','DD-MON-RR'),531,to_date('25-OCT-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (489,'181','Road drug instead marriage whom. Onto maybe consumer.',631,to_date('27-JUN-22','DD-MON-RR'),342,to_date('12-MAR-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (399,'183','Room well improve. Raise what month season study site force.',389,to_date('10-SEP-23','DD-MON-RR'),310,to_date('05-OCT-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (52,'184','Idea spend inside say manage message apply. Week cost always experience person scientist quickly.',996,to_date('01-DEC-24','DD-MON-RR'),491,to_date('29-OCT-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (93,'185','His important argue could candidate not. Become edge cover although best. Word cultural their show.',773,to_date('20-MAR-22','DD-MON-RR'),393,to_date('29-NOV-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (135,'186','Into exist lose stage along bad future. Quickly democratic believe attention tell.',596,to_date('20-NOV-24','DD-MON-RR'),119,to_date('27-MAR-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (119,'187','Allow else material agency thing. Cost would Democrat shake change ahead general.',688,to_date('22-AUG-22','DD-MON-RR'),313,to_date('16-OCT-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (401,'188','Trouble hope whom low bit impact. Beautiful officer drop debate whatever station old.',596,to_date('29-SEP-23','DD-MON-RR'),357,to_date('03-NOV-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (137,'190','Meet cut national fine. Summer size far their some.',718,to_date('29-OCT-20','DD-MON-RR'),216,to_date('06-FEB-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (318,'194','Bag smile sure everything exist believe. Identify everyone hit home it of hot voice.',233,to_date('28-FEB-20','DD-MON-RR'),493,to_date('11-MAY-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (92,'195','Test million room large institution if direction beyond.',244,to_date('08-APR-21','DD-MON-RR'),568,to_date('03-JAN-22','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (368,'196','Factor consider effort speech. Church stay respond base.',611,to_date('12-JUN-21','DD-MON-RR'),112,to_date('10-MAY-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (43,'198','War idea floor.
Appear idea film dinner. Tough nearly magazine final.',802,to_date('03-SEP-21','DD-MON-RR'),770,to_date('18-DEC-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (311,'199','Hand about return plant. Lawyer thought pull figure region true marriage.',24,to_date('21-OCT-22','DD-MON-RR'),724,to_date('28-SEP-21','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (259,'200','Night personal able dark miss. Source since marriage option model.
Onto work director want.',51,to_date('10-JUN-21','DD-MON-RR'),184,to_date('09-AUG-13','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (132,'203','He wear town agent. View dream exactly especially character base.',917,to_date('20-OCT-22','DD-MON-RR'),444,to_date('26-JUL-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (64,'204','When player involve hair sure air. Anyone less resource four prevent range issue.',750,to_date('26-OCT-24','DD-MON-RR'),418,to_date('28-APR-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (359,'205','What exist process your until exactly. Quickly water population class likely accept president.',631,to_date('15-MAY-21','DD-MON-RR'),923,to_date('01-FEB-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (90,'206','Position physical not peace approach government reveal.',339,to_date('19-MAY-22','DD-MON-RR'),423,to_date('20-DEC-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (37,'208','Exactly clear tell cell grow drop. Kind cup soldier those begin director fact.',260,to_date('06-JAN-24','DD-MON-RR'),626,to_date('16-NOV-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (166,'209','Page bar nearly month. High ten region single responsibility eye administration.',415,to_date('04-NOV-21','DD-MON-RR'),580,to_date('28-FEB-17','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (294,'210','Thought fly suggest behavior. Area three whole.
His that later case there seem.',355,to_date('19-DEC-23','DD-MON-RR'),813,to_date('13-APR-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (266,'212','Remember billion budget born. Discover simply environment.
Particular feel skin expert.',352,to_date('29-AUG-20','DD-MON-RR'),999,to_date('12-APR-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (447,'213','Chance much air exactly. Whole individual item notice brother fear poor.',591,to_date('15-DEC-23','DD-MON-RR'),687,to_date('27-FEB-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (221,'214','None human recently main.',945,to_date('05-OCT-23','DD-MON-RR'),416,to_date('22-NOV-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (123,'215','One play friend green hospital on. Social season less lay situation bed final.',682,to_date('03-AUG-22','DD-MON-RR'),392,to_date('30-APR-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (453,'216','List page firm open Democrat without.',934,to_date('09-MAY-21','DD-MON-RR'),919,to_date('04-OCT-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (357,'220','Television medical friend. Who particular such begin.',305,to_date('15-SEP-22','DD-MON-RR'),545,to_date('25-JUL-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (250,'221','Behind quickly full plant. Election quite though interesting what court.',454,to_date('27-OCT-22','DD-MON-RR'),683,to_date('11-OCT-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (283,'222','Star long parent just. Return send cut tonight last.',361,to_date('14-JAN-23','DD-MON-RR'),653,to_date('12-OCT-16','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (483,'223','South wait east here line major. Point citizen drive scene compare man also crime.',30,to_date('17-MAY-21','DD-MON-RR'),118,to_date('12-DEC-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (116,'224','However smile detail. Practice ahead his.',615,to_date('29-AUG-22','DD-MON-RR'),840,to_date('14-JUL-18','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (27,'227','Fill beautiful occur hair evidence. Also without kind public. Toward lot growth white.',488,to_date('21-MAY-22','DD-MON-RR'),812,to_date('21-FEB-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (207,'229','Employee certainly hotel all. Cup difficult how upon.',817,to_date('07-APR-20','DD-MON-RR'),924,to_date('24-MAR-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (215,'230','Data however office. Seven air despite shake possible. Weight garden pattern ready physical wall.',951,to_date('29-MAR-23','DD-MON-RR'),647,to_date('14-JAN-14','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (75,'232','Beyond artist face report place. Reality receive force left special.',422,to_date('15-FEB-21','DD-MON-RR'),357,to_date('25-JUL-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (53,'234','Forget since force into dinner Republican ability. Toward tonight reality down government.',726,to_date('26-JAN-21','DD-MON-RR'),327,to_date('31-MAR-20','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (322,'236','Blood sometimes message her teach. Debate by road western worker.',60,to_date('25-FEB-22','DD-MON-RR'),952,to_date('21-FEB-19','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (124,'238','Million down none. Least east test inside sport accept floor anything.',248,to_date('15-JUL-22','DD-MON-RR'),111,to_date('10-OCT-15','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (497,'239','Shoulder sound political child first skill prove admit. Card there glass play.',836,to_date('16-OCT-20','DD-MON-RR'),635,to_date('16-OCT-11','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (216,'241','Left by we sing generation. Radio difference simply wind protect environment.',306,to_date('18-JAN-22','DD-MON-RR'),536,to_date('18-MAR-12','DD-MON-RR'));
Insert into ITEM (ITEM_ID,RECEIPT_ID,ITEM_DESC,PRICE,EXP_DATE,QTY,ITEM_ADDDATE) values (371,'242','Home fast while which occur join skin. Suddenly this threat reduce.',792,to_date('19-FEB-20','DD-MON-RR'),950,to_date('13-DEC-13','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index SYS_C0032452
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0032452" ON "ADMIN"."ITEM" ("ITEM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ITEM" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ITEM" MODIFY ("EXP_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ITEM" MODIFY ("QTY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ITEM" ADD PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
