-------------------------------------------------------------------------------
-- USER CREATION SCRIPTS
-------------------------------------------------------------------------------

CREATE USER INVENTORY_MANAGER IDENTIFIED BY Admin123456789;

GRANT EXECUTE ANY TYPE,
EXECUTE ANY PROCEDURE,
ALTER ANY PROCEDURE, 
CREATE ANY TABLE, 
UNLIMITED TABLESPACE, 
DROP ANY TRIGGER, 
CREATE ANY PROCEDURE,
ALTER ANY INDEX, 
CREATE ANY INDEX, 
CREATE TABLE, 
CREATE SESSION, 
DROP ANY TYPE, 
CREATE ANY TRIGGER, 
CREATE SEQUENCE, 
DROP ANY INDEX, 
SELECT ANY TABLE, 
DROP ANY TABLE, 
CREATE ANY TYPE, 
ALTER ANY TRIGGER, 
ALTER ANY SEQUENCE, 
CREATE ANY SEQUENCE, 
UPDATE ANY TABLE, 
CREATE TRIGGER, 
DROP ANY PROCEDURE, 
DROP ANY SEQUENCE, 
CREATE ANY VIEW, 
DELETE ANY TABLE, 
INSERT ANY TABLE, 
ALTER ANY TABLE, 
READ ANY TABLE, 
DEBUG CONNECT SESSION, 
MERGE ANY VIEW, 
ALTER ANY TYPE, 
CREATE PROCEDURE, 
SELECT ANY SEQUENCE, 
DROP ANY VIEW, 
CREATE VIEW to INVENTORY_MANAGER;

CREATE USER SUPERVISOR IDENTIFIED BY Admin123456789;

GRANT CREATE SESSION TO SUPERVISOR;