CREATE OR REPLACE FUNCTION DATE_CHECK (
    CHANGE_DATE IN DATE
) RETURN NUMBER IS
    VALID NUMBER := 2;
BEGIN
    IF TRUNC(TO_DATE(CHANGE_DATE)) >= TRUNC(SYSDATE) THEN
        VALID := 1;
    END IF;
    RETURN VALID;
END;
/