--DISPLAY THE REPORTS FOR RETURNING ITEMS THAT HAVE PASSED THEIR EXPIRATION DATE TO THE RESPECTIVE VENDOR WITH A PRICE REDUCTION.
CREATE OR REPLACE VIEW EXPIRED_GOODS_RETURN AS
    SELECT
        A.ITEM_ID,
        A.RECEIPT_ID,
        A.ITEM_DESC,
        A.PRICE,
        A.PRICE * 0.10           AS TEN_PERCENT_DISCOUNT,
        A.PRICE - A.PRICE * 0.10 AS REDUCED_PRICE, --10% DISCOUNT REDUCTION, CHANGE TO WHATEVER NEEDED 
        A.EXP_DATE,
        A.QTY,
        A.ITEM_ADDDATE,
        B.PO_ID,
        C.VENDOR_ID,
        D.VENDOR_NAME
    FROM
        ITEM           A,
        RECEIPT        B,
        PURCHASE_ORDER C,
        VENDOR         D
    WHERE
            A.EXP_DATE <= SYSDATE
        AND A.RECEIPT_ID = B.RECEIPT_ID
        AND B.PO_ID = C.PO_ID
        AND C.VENDOR_ID = D.VENDOR_ID;
        
SELECT * FROM EXPIRED_GOODS_RETURN WHERE ROWNUM <= 10;
