--------------------------------------------------------
--  DDL for Table LOG
--------------------------------------------------------

DECLARE
  nb NUMBER;
BEGIN
  SELECT count(*) INTO nb FROM user_tables 
    WHERE TABLE_NAME = 'LOG';
  IF nb = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE LOG(
      LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
      ERROR_CODE NUMBER NOT NULL,
      PROCEDURE_NAME VARCHAR(50) NOT NULL,
      RUN VARCHAR(20),
      PRIMARY KEY(LOG_ID)
    )';
 END IF;
END;

