
-------------------------------------------------------------------------------
--DDL FOR RECEIPT_DETAIL (CREATE TABLE RECEIPT_DETAIL)
-------------------------------------------------------------------------------

DECLARE NB NUMBER;
BEGIN
    SELECT COUNT(*) INTO NB FROM USER_TABLES
    WHERE TABLE_NAME = 'RECEIPT_DETAIL';

    IF NB = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE RECEIPT_DETAIL ( 
        RECEIPT_DETAIL_ID VARCHAR(20),
        DROP_ID NUMBER ,
        ITEM_ID NUMBER ,
        RECEIPT_ID NUMBER ,
        QTY NUMBER,
        PRIMARY KEY(RECEIPT_DETAIL_ID),
        CONSTRAINT FK_RI2 FOREIGN KEY (RECEIPT_ID)  REFERENCES RECEIPT (RECEIPT_ID) ON DELETE CASCADE,
        CONSTRAINT FK_ITEM2 FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID) ON DELETE CASCADE,
        CONSTRAINT FK_DROPID2 FOREIGN KEY (DROP_ID) REFERENCES DROPID (DROP_ID) ON DELETE CASCADE)';
    END IF;
    DBMS_OUTPUT.PUT_LINE ('TABLE RECEIPT_DETAIL CREATED');
END;
/