
--------------------------------------------------------
--  DDL for Table RECEIPT
--------------------------------------------------------

DECLARE
  nb NUMBER;
BEGIN
  SELECT count(*) INTO nb FROM user_tables 
    WHERE TABLE_NAME = 'RECEIPT';
  IF nb = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE RECEIPT(
      RECEIPT_ID NUMBER NOT NULL,
      PO_ID NUMBER NOT NULL,
      STATUS VARCHAR(30) NOT NULL,
      RECEIPT_DATE DATE NOT NULL,
      CONSTRAINT PK_RECEIPT 
      PRIMARY KEY(RECEIPT_ID),
      CONSTRAINT FK_RECEIPT
      FOREIGN KEY(PO_ID)
      REFERENCES PURCHASE_ORDER(PO_ID)
      
      )';
 END IF;
END;
/

--------------------------------------------------------
--  INSERT for Table RECEIPT
--------------------------------------------------------

Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (1,1,to_date('05-AUG-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (2,2,to_date('07-JUN-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (3,3,to_date('04-JAN-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (4,4,to_date('24-JUN-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (5,5,to_date('09-JAN-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (6,6,to_date('15-JAN-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (7,7,to_date('09-MAY-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (8,8,to_date('02-OCT-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (9,9,to_date('15-JUN-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (10,10,to_date('12-MAY-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (11,11,to_date('09-NOV-18','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (12,12,to_date('23-DEC-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (13,13,to_date('20-APR-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (14,14,to_date('11-MAY-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (15,15,to_date('10-OCT-12','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (16,16,to_date('27-JUL-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (17,17,to_date('11-MAR-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (18,18,to_date('15-MAY-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (19,19,to_date('20-NOV-10','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (20,20,to_date('09-JUN-13','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (21,21,to_date('31-MAR-22','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (22,22,to_date('01-DEC-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (23,23,to_date('03-APR-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (24,24,to_date('14-MAY-19','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (25,25,to_date('07-JUL-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (26,26,to_date('21-MAR-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (27,27,to_date('04-FEB-20','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (28,28,to_date('11-FEB-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (29,29,to_date('02-OCT-13','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (30,30,to_date('24-DEC-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (31,31,to_date('06-APR-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (32,32,to_date('11-AUG-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (33,33,to_date('21-SEP-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (34,34,to_date('18-APR-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (35,35,to_date('09-DEC-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (36,36,to_date('26-NOV-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (37,37,to_date('14-JUN-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (38,38,to_date('01-JUN-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (39,39,to_date('23-MAR-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (40,40,to_date('09-MAY-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (41,41,to_date('08-JUL-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (42,42,to_date('16-JUL-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (43,43,to_date('15-MAY-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (44,44,to_date('04-OCT-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (45,45,to_date('03-DEC-12','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (46,46,to_date('15-FEB-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (47,47,to_date('04-JUN-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (48,48,to_date('09-DEC-16','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (49,49,to_date('10-OCT-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (50,50,to_date('26-APR-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (51,51,to_date('26-AUG-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (52,52,to_date('26-JUL-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (53,53,to_date('01-FEB-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (54,54,to_date('14-JUL-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (55,55,to_date('27-AUG-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (56,56,to_date('11-APR-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (57,57,to_date('03-JAN-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (58,58,to_date('01-MAY-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (59,59,to_date('15-NOV-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (60,60,to_date('14-OCT-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (61,61,to_date('25-JUN-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (62,62,to_date('22-SEP-13','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (63,63,to_date('26-JUL-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (64,64,to_date('20-MAY-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (65,65,to_date('11-SEP-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (66,66,to_date('17-APR-10','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (67,67,to_date('21-APR-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (68,68,to_date('18-NOV-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (69,69,to_date('08-APR-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (70,70,to_date('19-FEB-15','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (71,71,to_date('18-AUG-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (72,72,to_date('28-NOV-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (73,73,to_date('26-DEC-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (74,74,to_date('11-DEC-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (75,75,to_date('02-FEB-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (76,76,to_date('04-FEB-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (77,77,to_date('06-AUG-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (78,78,to_date('14-MAY-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (79,79,to_date('30-SEP-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (80,80,to_date('14-AUG-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (81,81,to_date('16-JUL-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (82,82,to_date('30-AUG-18','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (83,83,to_date('03-DEC-13','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (84,84,to_date('13-JUL-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (85,85,to_date('25-JUN-20','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (86,86,to_date('11-FEB-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (87,87,to_date('11-DEC-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (88,88,to_date('17-JUN-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (89,89,to_date('25-APR-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (90,90,to_date('09-MAR-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (91,91,to_date('19-FEB-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (92,92,to_date('12-JUN-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (93,93,to_date('20-FEB-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (94,94,to_date('10-FEB-16','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (95,95,to_date('08-MAR-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (96,96,to_date('18-NOV-12','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (97,97,to_date('31-JAN-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (98,98,to_date('12-FEB-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (99,99,to_date('11-MAR-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (100,100,to_date('24-JUL-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (101,101,to_date('12-DEC-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (102,102,to_date('28-OCT-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (103,103,to_date('25-JUN-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (104,104,to_date('21-APR-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (105,105,to_date('11-JUN-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (106,106,to_date('25-JAN-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (107,107,to_date('13-NOV-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (108,108,to_date('06-FEB-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (109,109,to_date('30-SEP-15','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (110,110,to_date('28-DEC-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (111,111,to_date('03-MAY-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (112,112,to_date('14-MAR-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (113,113,to_date('05-MAY-10','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (114,114,to_date('05-JUN-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (115,115,to_date('17-OCT-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (116,116,to_date('22-FEB-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (117,117,to_date('04-FEB-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (118,118,to_date('15-SEP-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (119,119,to_date('21-FEB-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (120,120,to_date('17-MAY-18','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (121,121,to_date('23-JAN-10','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (122,122,to_date('05-DEC-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (123,123,to_date('03-SEP-15','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (124,124,to_date('03-APR-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (125,125,to_date('21-FEB-10','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (126,126,to_date('29-APR-10','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (127,127,to_date('17-JUL-13','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (128,128,to_date('31-AUG-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (129,129,to_date('19-MAY-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (130,130,to_date('10-FEB-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (131,131,to_date('08-APR-15','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (132,132,to_date('29-JAN-22','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (133,133,to_date('16-FEB-22','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (134,134,to_date('24-JUL-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (135,135,to_date('21-APR-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (136,136,to_date('09-MAY-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (137,137,to_date('24-SEP-20','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (138,138,to_date('11-DEC-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (139,139,to_date('11-JAN-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (140,140,to_date('04-MAY-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (141,141,to_date('05-NOV-13','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (142,142,to_date('08-JAN-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (143,143,to_date('01-FEB-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (144,144,to_date('10-FEB-16','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (145,145,to_date('25-NOV-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (146,146,to_date('27-JUL-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (147,147,to_date('24-SEP-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (148,148,to_date('26-DEC-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (149,149,to_date('04-JUL-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (150,150,to_date('02-OCT-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (151,151,to_date('29-AUG-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (152,152,to_date('03-SEP-13','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (153,153,to_date('28-OCT-18','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (154,154,to_date('20-JUN-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (155,155,to_date('29-JAN-10','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (156,156,to_date('07-SEP-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (157,157,to_date('22-SEP-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (158,158,to_date('17-SEP-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (159,159,to_date('17-FEB-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (160,160,to_date('23-OCT-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (161,161,to_date('19-JAN-22','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (162,162,to_date('02-JAN-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (163,163,to_date('15-SEP-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (164,164,to_date('08-NOV-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (165,165,to_date('05-FEB-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (166,166,to_date('06-NOV-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (167,167,to_date('18-APR-16','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (168,168,to_date('17-OCT-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (169,169,to_date('14-JAN-12','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (170,170,to_date('24-OCT-13','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (171,171,to_date('30-NOV-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (172,172,to_date('07-MAY-10','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (173,173,to_date('30-DEC-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (174,174,to_date('30-JUL-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (175,175,to_date('24-JUN-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (176,176,to_date('24-FEB-16','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (177,177,to_date('20-JUL-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (178,178,to_date('09-APR-15','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (179,179,to_date('14-MAY-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (180,180,to_date('30-AUG-15','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (181,181,to_date('04-FEB-13','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (182,182,to_date('18-MAY-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (183,183,to_date('20-MAR-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (184,184,to_date('03-DEC-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (185,185,to_date('30-APR-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (186,186,to_date('02-MAR-22','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (187,187,to_date('10-JUN-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (188,188,to_date('25-OCT-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (189,189,to_date('15-JAN-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (190,190,to_date('01-JUL-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (191,191,to_date('22-MAY-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (192,192,to_date('17-APR-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (193,193,to_date('18-JUL-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (194,194,to_date('05-DEC-13','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (195,195,to_date('06-JAN-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (196,196,to_date('31-JAN-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (197,197,to_date('18-APR-15','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (198,198,to_date('05-FEB-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (199,199,to_date('10-JUN-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (200,200,to_date('05-MAY-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (201,201,to_date('14-MAR-22','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (202,202,to_date('20-JUL-13','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (203,203,to_date('24-NOV-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (204,204,to_date('19-NOV-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (205,205,to_date('03-FEB-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (206,206,to_date('15-MAY-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (207,207,to_date('20-APR-15','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (208,208,to_date('27-OCT-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (209,209,to_date('24-MAR-18','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (210,210,to_date('01-JUN-19','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (211,211,to_date('25-MAY-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (212,212,to_date('27-MAR-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (213,213,to_date('11-NOV-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (214,214,to_date('18-AUG-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (215,215,to_date('15-JUN-10','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (216,216,to_date('10-MAY-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (217,217,to_date('03-FEB-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (218,218,to_date('16-OCT-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (219,219,to_date('02-SEP-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (220,220,to_date('11-APR-19','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (221,221,to_date('05-MAR-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (222,222,to_date('23-JUL-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (223,223,to_date('27-JAN-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (224,224,to_date('13-FEB-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (225,225,to_date('23-MAY-20','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (226,226,to_date('01-FEB-12','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (227,227,to_date('27-MAR-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (228,228,to_date('21-SEP-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (229,229,to_date('24-MAY-10','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (230,230,to_date('27-NOV-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (231,231,to_date('18-SEP-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (232,232,to_date('05-DEC-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (233,233,to_date('31-JAN-16','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (234,234,to_date('04-NOV-19','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (235,235,to_date('03-MAR-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (236,236,to_date('13-APR-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (237,237,to_date('17-OCT-10','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (238,238,to_date('11-AUG-15','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (239,239,to_date('11-NOV-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (240,240,to_date('30-DEC-20','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (241,241,to_date('03-MAR-22','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (242,242,to_date('12-NOV-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (243,243,to_date('25-FEB-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (244,244,to_date('30-MAR-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (245,245,to_date('14-OCT-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (246,246,to_date('10-AUG-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (247,247,to_date('25-MAR-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (248,248,to_date('17-JUL-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (249,249,to_date('04-FEB-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (250,250,to_date('22-APR-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (251,251,to_date('18-SEP-10','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (252,252,to_date('11-FEB-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (253,253,to_date('04-AUG-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (254,254,to_date('11-FEB-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (255,255,to_date('01-MAR-22','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (256,256,to_date('21-APR-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (257,257,to_date('07-APR-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (258,258,to_date('22-OCT-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (259,259,to_date('01-JUN-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (260,260,to_date('20-MAY-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (261,261,to_date('03-APR-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (262,262,to_date('07-SEP-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (263,263,to_date('11-SEP-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (264,264,to_date('01-JAN-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (265,265,to_date('15-NOV-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (266,266,to_date('11-APR-19','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (267,267,to_date('14-DEC-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (268,268,to_date('30-JUL-13','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (269,269,to_date('04-AUG-18','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (270,270,to_date('30-OCT-19','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (271,271,to_date('20-JUN-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (272,272,to_date('31-JAN-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (273,273,to_date('18-AUG-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (274,274,to_date('24-MAR-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (275,275,to_date('10-AUG-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (276,276,to_date('09-MAR-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (277,277,to_date('17-MAR-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (278,278,to_date('06-DEC-19','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (279,279,to_date('21-AUG-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (280,280,to_date('20-FEB-22','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (281,281,to_date('07-MAY-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (282,282,to_date('24-JUL-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (283,283,to_date('19-OCT-16','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (284,284,to_date('09-MAY-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (285,285,to_date('23-APR-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (286,286,to_date('19-OCT-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (287,287,to_date('28-NOV-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (288,288,to_date('22-SEP-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (289,289,to_date('10-JUL-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (290,290,to_date('26-OCT-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (291,291,to_date('16-APR-22','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (292,292,to_date('08-DEC-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (293,293,to_date('06-MAY-13','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (294,294,to_date('20-APR-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (295,295,to_date('15-OCT-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (296,296,to_date('23-JUL-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (297,297,to_date('29-AUG-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (298,298,to_date('05-APR-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (299,299,to_date('19-MAY-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (300,300,to_date('19-MAR-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (301,301,to_date('08-JUN-16','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (302,302,to_date('04-FEB-13','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (303,303,to_date('09-JAN-18','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (304,304,to_date('25-MAY-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (305,305,to_date('11-MAR-22','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (306,306,to_date('28-NOV-18','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (307,307,to_date('19-NOV-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (308,308,to_date('15-DEC-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (309,309,to_date('09-JUN-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (310,310,to_date('20-JUL-10','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (311,311,to_date('27-NOV-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (312,312,to_date('21-MAR-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (313,313,to_date('24-OCT-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (314,314,to_date('30-OCT-15','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (315,315,to_date('26-FEB-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (316,316,to_date('19-NOV-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (317,317,to_date('15-DEC-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (318,318,to_date('15-JAN-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (319,319,to_date('15-AUG-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (320,320,to_date('12-MAR-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (321,321,to_date('04-JAN-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (322,322,to_date('21-JUL-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (323,323,to_date('02-DEC-12','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (324,324,to_date('17-FEB-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (325,325,to_date('19-FEB-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (326,326,to_date('25-JUL-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (327,327,to_date('06-AUG-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (328,328,to_date('25-SEP-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (329,329,to_date('22-SEP-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (330,330,to_date('05-JUN-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (331,331,to_date('17-DEC-13','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (332,332,to_date('09-MAR-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (333,333,to_date('21-NOV-10','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (334,334,to_date('20-FEB-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (335,335,to_date('15-JUL-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (336,336,to_date('07-MAY-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (337,337,to_date('09-DEC-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (338,338,to_date('15-JUN-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (339,339,to_date('14-MAR-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (340,340,to_date('03-DEC-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (341,341,to_date('16-MAY-15','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (342,342,to_date('05-FEB-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (343,343,to_date('04-SEP-19','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (344,344,to_date('27-JUL-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (345,345,to_date('28-MAR-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (346,346,to_date('02-MAR-22','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (347,347,to_date('10-DEC-15','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (348,348,to_date('18-MAR-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (349,349,to_date('04-AUG-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (350,350,to_date('12-APR-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (351,351,to_date('19-JUL-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (352,352,to_date('07-AUG-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (353,353,to_date('08-AUG-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (354,354,to_date('29-JAN-22','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (355,355,to_date('21-JUL-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (356,356,to_date('31-AUG-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (357,357,to_date('05-FEB-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (358,358,to_date('02-JUN-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (359,359,to_date('28-MAR-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (360,360,to_date('07-DEC-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (361,361,to_date('22-MAR-10','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (362,362,to_date('01-FEB-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (363,363,to_date('29-JAN-18','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (364,364,to_date('29-MAR-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (365,365,to_date('11-DEC-10','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (366,366,to_date('14-DEC-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (367,367,to_date('21-JUL-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (368,368,to_date('07-NOV-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (369,369,to_date('08-AUG-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (370,370,to_date('19-FEB-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (371,371,to_date('02-OCT-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (372,372,to_date('11-JUL-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (373,373,to_date('07-OCT-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (374,374,to_date('09-NOV-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (375,375,to_date('02-JAN-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (376,376,to_date('15-JUL-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (377,377,to_date('28-MAY-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (378,378,to_date('01-NOV-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (379,379,to_date('16-AUG-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (380,380,to_date('05-MAR-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (381,381,to_date('18-DEC-15','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (382,382,to_date('13-AUG-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (383,383,to_date('11-APR-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (384,384,to_date('02-MAR-16','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (385,385,to_date('01-OCT-14','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (386,386,to_date('09-MAR-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (387,387,to_date('14-APR-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (388,388,to_date('02-APR-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (389,389,to_date('24-OCT-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (390,390,to_date('25-JUL-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (391,391,to_date('23-FEB-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (392,392,to_date('12-JUL-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (393,393,to_date('18-FEB-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (394,394,to_date('23-FEB-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (395,395,to_date('13-AUG-20','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (396,396,to_date('01-SEP-20','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (397,397,to_date('26-DEC-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (398,398,to_date('19-MAY-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (399,399,to_date('18-JUN-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (400,400,to_date('13-MAY-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (401,401,to_date('02-APR-15','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (402,402,to_date('27-APR-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (403,403,to_date('03-SEP-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (404,404,to_date('19-SEP-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (405,405,to_date('23-OCT-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (406,406,to_date('23-DEC-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (407,407,to_date('04-JUL-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (408,408,to_date('09-OCT-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (409,409,to_date('12-NOV-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (410,410,to_date('01-JAN-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (411,411,to_date('29-OCT-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (412,412,to_date('30-AUG-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (413,413,to_date('15-MAR-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (414,414,to_date('30-JAN-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (415,415,to_date('29-MAR-12','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (416,416,to_date('15-MAR-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (417,417,to_date('15-OCT-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (418,418,to_date('23-JUN-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (419,419,to_date('19-JAN-22','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (420,420,to_date('31-JUL-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (421,421,to_date('15-APR-21','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (422,422,to_date('08-JUN-11','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (423,423,to_date('28-NOV-13','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (424,424,to_date('23-MAR-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (425,425,to_date('17-FEB-20','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (426,426,to_date('06-OCT-13','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (427,427,to_date('26-FEB-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (428,428,to_date('21-AUG-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (429,429,to_date('01-JUL-12','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (430,430,to_date('24-MAR-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (431,431,to_date('05-OCT-16','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (432,432,to_date('01-JUN-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (433,433,to_date('09-JUN-10','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (434,434,to_date('19-OCT-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (435,435,to_date('23-MAR-18','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (436,436,to_date('01-NOV-12','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (437,437,to_date('16-JUL-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (438,438,to_date('07-MAY-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (439,439,to_date('22-MAR-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (440,440,to_date('20-DEC-16','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (441,441,to_date('30-MAY-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (442,442,to_date('06-OCT-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (443,443,to_date('10-JUL-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (444,444,to_date('31-OCT-12','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (445,445,to_date('10-JAN-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (446,446,to_date('02-JUN-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (447,447,to_date('15-NOV-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (448,448,to_date('24-NOV-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (449,449,to_date('01-APR-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (450,450,to_date('13-JUL-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (451,451,to_date('18-JUL-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (452,452,to_date('02-DEC-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (453,453,to_date('29-OCT-15','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (454,454,to_date('21-NOV-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (455,455,to_date('25-OCT-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (456,456,to_date('04-JUL-19','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (457,457,to_date('13-JUN-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (458,458,to_date('26-DEC-16','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (459,459,to_date('01-MAY-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (460,460,to_date('26-APR-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (461,461,to_date('17-SEP-10','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (462,462,to_date('01-DEC-15','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (463,463,to_date('27-NOV-15','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (464,464,to_date('23-OCT-15','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (465,465,to_date('20-SEP-14','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (466,466,to_date('07-JAN-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (467,467,to_date('02-MAY-17','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (468,468,to_date('09-OCT-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (469,469,to_date('11-MAY-15','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (470,470,to_date('27-DEC-20','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (471,471,to_date('27-NOV-10','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (472,472,to_date('11-MAY-17','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (473,473,to_date('06-OCT-11','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (474,474,to_date('13-DEC-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (475,475,to_date('16-MAR-16','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (476,476,to_date('17-NOV-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (477,477,to_date('21-OCT-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (478,478,to_date('25-FEB-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (479,479,to_date('24-AUG-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (480,480,to_date('25-JUL-20','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (481,481,to_date('08-NOV-12','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (482,482,to_date('27-DEC-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (483,483,to_date('28-SEP-11','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (484,484,to_date('16-FEB-20','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (485,485,to_date('15-MAY-18','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (486,486,to_date('01-JUN-18','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (487,487,to_date('10-JUL-10','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (488,488,to_date('08-JUN-21','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (489,489,to_date('18-JUL-15','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (490,490,to_date('19-FEB-17','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (491,491,to_date('13-NOV-20','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (492,492,to_date('01-MAR-14','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (493,493,to_date('08-APR-10','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (494,494,to_date('24-APR-12','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (495,495,to_date('06-JAN-21','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (496,496,to_date('10-OCT-20','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (497,497,to_date('22-JAN-19','DD-MON-RR'),'New');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (498,498,to_date('19-JUL-12','DD-MON-RR'),'Received');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (499,499,to_date('14-APR-22','DD-MON-RR'),'Closed');
Insert into RECEIPT (RECEIPT_ID,PO_ID,RECEIPT_DATE,STATUS) values (500,500,to_date('04-JUN-14','DD-MON-RR'),'New');
--------------------------------------------------------
--  DDL for Index SYS_C0032338
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SYS_C0032338" ON "ADMIN"."RECEIPT" ("RECEIPT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table RECEIPT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RECEIPT" MODIFY ("RECEIPT_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RECEIPT" MODIFY ("PO_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RECEIPT" MODIFY ("RECEIPT_DATE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RECEIPT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RECEIPT" ADD PRIMARY KEY ("RECEIPT_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECEIPT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RECEIPT" ADD FOREIGN KEY ("PO_ID")
	  REFERENCES "ADMIN"."PURCHASE_ORDER" ("PO_ID") ENABLE;
