
CREATE OR REPLACE TRIGGER DECREASEQTY
AFTER UPDATE ON ORDERS FOR EACH ROW WHEN (NEW.STATUS = 'SHIPPED')
DECLARE
    --ORDER_ID NUMBER:= :NEW.ORDER_ID;
    CURSOR ORDER_ITEMS
    IS
      SELECT ITEM_ID, QTY 
      FROM ORDER_DETAILS
      WHERE ORDER_ID = :NEW.ORDER_ID;
BEGIN 

    FOR ITEM_DETAILS IN ORDER_ITEMS
    LOOP
        UPDATE ITEM SET QTY = QTY-ITEM_DETAILS.QTY WHERE ITEM_ID = ITEM_DETAILS.ITEM_ID;
        UPDATE ITEMXLOC SET QTY = QTY-ITEM_DETAILS.QTY WHERE ITEM_ID = ITEM_DETAILS.ITEM_ID;
        UPDATE ITEMXLOCXID SET QTY = QTY-ITEM_DETAILS.QTY WHERE ITEM_ID = ITEM_DETAILS.ITEM_ID;

    END LOOP;
END;
/
