SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER decreaseQty
AFTER UPDATE ON ORDERS FOR EACH ROW WHEN (NEW.STATUS = 'Shipped')
DECLARE
    --order_id NUMBER:= :NEW.ORDER_ID;
    CURSOR ORDER_ITEMS
    IS
      SELECT ITEM_ID, QTY 
      FROM ORDER_DETAILS
      WHERE ORDER_ID = :NEW.ORDER_ID;
BEGIN 
      
    FOR ITEM_DETAILS IN ORDER_ITEMS
    LOOP
        dbms_output.put_line(ITEM_DETAILS.ITEM_ID);
        dbms_output.put_line(ITEM_DETAILS.QTY);
        UPDATE ITEM SET qty = qty-ITEM_DETAILS.QTY WHERE item_id = ITEM_DETAILS.ITEM_ID;
    END LOOP;
END;

SELECT * FROM ORDERS;
SELECT * FROM ITEM WHERE ITEM_ID = 356;
SELECT * FROM order_details;

UPDATE ORDERS
	SET STATUS = 'Shipped'
	WHERE ORDER_ID = 438;
    
EXECUTE decreaseQty;