--------------------------------------------------------
--  DDL for Table LOG
--------------------------------------------------------

DECLARE
  nb NUMBER;
BEGIN
  SELECT count(*) INTO nb FROM user_tables 
    WHERE TABLE_NAME = 'NCOUNTER';
  IF nb = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE NCOUNTER(
      SERIAL_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
      TABLE_NAME VARCHAR(30) NOT NULL,
      MAX_COUNT VARCHAR(32) NOT NULL,
      CURRENT_COUNT VARCHAR(32) NOT NULL,
      PRIMARY KEY(SERIAL_ID)
    )';
 END IF;
END;