CREATE OR REPLACE PROCEDURE ORDER_PICKING
AS
   VAR_ORDERID   VARCHAR2 (10);
    TASKNEWTOPICKSTATUS  VARCHAR2 (10);

   CURSOR CUR_ORDER
   IS
      SELECT DISTINCT O.ORDER_ID 
        FROM ORDER_DETAILS OD JOIN ORDERS O ON O.ORDER_ID = OD.ORDER_ID
       WHERE STATUS = 'ORDERED';
BEGIN
FOR RCUR_ORDER IN CUR_ORDER
   LOOP
      BEGIN
         VAR_ORDERID := RCUR_ORDER.ORDER_ID;
         MERGE INTO ORDERS B
              USING (SELECT DISTINCT OD.ITEM_ID, OD.QTY,O.ORDER_ID
                       FROM ORDER_DETAILS OD JOIN ORDERS O ON O.ORDER_ID = OD.ORDER_ID
                      WHERE OD.ORDER_ID = VAR_ORDERID ) E
                 ON (E.ORDER_ID = B.ORDER_ID)
         WHEN MATCHED
         THEN
            UPDATE SET STATUS = 'PICKING'
            WHERE STATUS = 'ORDERED' AND ORDER_ID = VAR_ORDERID;  
DBMS_OUTPUT.PUT_LINE ('ORDER IN PICKING');


             TASKNEWTOPICKSTATUS:=TASK_NEW_TO_PICK();

             END;
            END LOOP;
        END;
/